version: "3"
services:
  webserver:
    image: bettermood/apache
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - "./docker/apache2_mailhog.conf:/etc/apache2/conf-enabled/apache2_mailhog.conf"
      - "./docker/apache2_faildump.conf:/etc/apache2/conf-enabled/apache2_faildump.conf"
    depends_on:
      - php
    environment:
      PHP_SERVER: php
  php:
    image: bettermood/php-xdebug
    volumes:
      - ./:/var/www/html
      - behat_data:${MOODLE_DOCKER_BEHAT_DATAROOT}
      - moodle_data:${MOODLE_DOCKER_DATAROOT}
      - phpunit_data:${MOODLE_DOCKER_PHPUNIT_DATAROOT}
    env_file:
      - .env
  phpunit: # container to run phpunit tests
    image: bettermood/php
    volumes:
      - ./:/var/www/html
      - behat_data:${MOODLE_DOCKER_BEHAT_DATAROOT}
      - moodle_data:${MOODLE_DOCKER_DATAROOT}
      - phpunit_data:${MOODLE_DOCKER_PHPUNIT_DATAROOT}
    env_file:
      - .env
  behat:
    image: bettermood/php
    depends_on:
      - webserver
    volumes:
      - ./:/var/www/html
      - behat_data:${MOODLE_DOCKER_BEHAT_DATAROOT}
      - moodle_data:${MOODLE_DOCKER_DATAROOT}
      - phpunit_data:${MOODLE_DOCKER_PHPUNIT_DATAROOT}
    env_file:
      - .env
    environment:
      MOODLE_DOCKER_BROWSER: firefox
      PHP_IDE_CONFIG: "serverName=localhost"
  mysql:
    image: mysql:5
    ports:
      - 33306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MOODLE_DOCKER_DBNAME}
      MYSQL_ROOT_PASSWORD: ${MOODLE_DOCKER_DBPASS}
      MYSQL_USER: ${MOODLE_DOCKER_DBUSER}
      MYSQL_PASSWORD: ${MOODLE_DOCKER_DBPASS}
  exttests: # Test files for phpunit tests using external data
    image: moodlehq/moodle-exttests
  selenium:
    image: "selenium/standalone-firefox:2.53.1"
    volumes:
      - ./:/var/www/html
  mailhog:
      image: mailhog/mailhog
volumes:
  moodle_data:
  behat_data:
  phpunit_data:
  mysql_data:
